// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdProtocol.proto

package com.lbwan.game.proto;

public final class CmdProtocol {
  private CmdProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    CMD_INIT_GAME_DESKTOP_INFO(0, 1101),
    CMD_CUT_DOWN_SECS_SYNC(1, 1102),
    CMD_SUMBIT_SOME_PORKER(2, 1103),
    CMD_SUMBIT_NULL_PORKER(3, 1104),
    CMD_SUMBIT_PORKER_RESULT(4, 1105),
    CMD_GAME_END_OF_RESULT(5, 1106),
    CMD_SERVER_NOTIFY_PAY_TRIBUTE(6, 1107),
    CMD_PAY_TRIBUTE_REQUEST(7, 1108),
    CMD_PAY_TRIBUTE_RESULT(8, 1109),
    CMD_SERVER_NOTIFY_BACK_TRIBUTE(9, 1110),
    CMD_BACK_TRIBUTE_REQUEST(10, 1111),
    CMD_BACK_TRIBUTE_RESPONSE(11, 1112),
    CMD_REQUEST_GAME_INIT_INFO(12, 1113),
    CMD_PAY_TRIBUTE_NOTIFY_ALL(13, 1114),
    CMD_BACK_TRIBUTE_NOTIFY_ALL(14, 1115),
    CMD_NEED_HOSTING_PORKER(15, 1116),
    CMD_CANCEL_HOSTING_PORKER(16, 1117),
    CMD_GOLD_SYNC_TO_CLIENT(17, 1118),
    CMD_SERVER_NOTIFY_GROUND(18, 1119),
    CMD_SERVER_NOTIFY_MAX_PORKER(19, 1120),
    CMD_GAME_SEND_CHAT(20, 1121),
    CMD_GAME_GET_CHAT(21, 1122),
    ;
    
    public static final int CMD_INIT_GAME_DESKTOP_INFO_VALUE = 1101;
    public static final int CMD_CUT_DOWN_SECS_SYNC_VALUE = 1102;
    public static final int CMD_SUMBIT_SOME_PORKER_VALUE = 1103;
    public static final int CMD_SUMBIT_NULL_PORKER_VALUE = 1104;
    public static final int CMD_SUMBIT_PORKER_RESULT_VALUE = 1105;
    public static final int CMD_GAME_END_OF_RESULT_VALUE = 1106;
    public static final int CMD_SERVER_NOTIFY_PAY_TRIBUTE_VALUE = 1107;
    public static final int CMD_PAY_TRIBUTE_REQUEST_VALUE = 1108;
    public static final int CMD_PAY_TRIBUTE_RESULT_VALUE = 1109;
    public static final int CMD_SERVER_NOTIFY_BACK_TRIBUTE_VALUE = 1110;
    public static final int CMD_BACK_TRIBUTE_REQUEST_VALUE = 1111;
    public static final int CMD_BACK_TRIBUTE_RESPONSE_VALUE = 1112;
    public static final int CMD_REQUEST_GAME_INIT_INFO_VALUE = 1113;
    public static final int CMD_PAY_TRIBUTE_NOTIFY_ALL_VALUE = 1114;
    public static final int CMD_BACK_TRIBUTE_NOTIFY_ALL_VALUE = 1115;
    public static final int CMD_NEED_HOSTING_PORKER_VALUE = 1116;
    public static final int CMD_CANCEL_HOSTING_PORKER_VALUE = 1117;
    public static final int CMD_GOLD_SYNC_TO_CLIENT_VALUE = 1118;
    public static final int CMD_SERVER_NOTIFY_GROUND_VALUE = 1119;
    public static final int CMD_SERVER_NOTIFY_MAX_PORKER_VALUE = 1120;
    public static final int CMD_GAME_SEND_CHAT_VALUE = 1121;
    public static final int CMD_GAME_GET_CHAT_VALUE = 1122;
    
    
    public final int getNumber() { return value; }
    
    public static CmdType valueOf(int value) {
      switch (value) {
        case 1101: return CMD_INIT_GAME_DESKTOP_INFO;
        case 1102: return CMD_CUT_DOWN_SECS_SYNC;
        case 1103: return CMD_SUMBIT_SOME_PORKER;
        case 1104: return CMD_SUMBIT_NULL_PORKER;
        case 1105: return CMD_SUMBIT_PORKER_RESULT;
        case 1106: return CMD_GAME_END_OF_RESULT;
        case 1107: return CMD_SERVER_NOTIFY_PAY_TRIBUTE;
        case 1108: return CMD_PAY_TRIBUTE_REQUEST;
        case 1109: return CMD_PAY_TRIBUTE_RESULT;
        case 1110: return CMD_SERVER_NOTIFY_BACK_TRIBUTE;
        case 1111: return CMD_BACK_TRIBUTE_REQUEST;
        case 1112: return CMD_BACK_TRIBUTE_RESPONSE;
        case 1113: return CMD_REQUEST_GAME_INIT_INFO;
        case 1114: return CMD_PAY_TRIBUTE_NOTIFY_ALL;
        case 1115: return CMD_BACK_TRIBUTE_NOTIFY_ALL;
        case 1116: return CMD_NEED_HOSTING_PORKER;
        case 1117: return CMD_CANCEL_HOSTING_PORKER;
        case 1118: return CMD_GOLD_SYNC_TO_CLIENT;
        case 1119: return CMD_SERVER_NOTIFY_GROUND;
        case 1120: return CMD_SERVER_NOTIFY_MAX_PORKER;
        case 1121: return CMD_GAME_SEND_CHAT;
        case 1122: return CMD_GAME_GET_CHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lbwan.game.proto.CmdProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CmdType[] VALUES = {
      CMD_INIT_GAME_DESKTOP_INFO, CMD_CUT_DOWN_SECS_SYNC, CMD_SUMBIT_SOME_PORKER, CMD_SUMBIT_NULL_PORKER, CMD_SUMBIT_PORKER_RESULT, CMD_GAME_END_OF_RESULT, CMD_SERVER_NOTIFY_PAY_TRIBUTE, CMD_PAY_TRIBUTE_REQUEST, CMD_PAY_TRIBUTE_RESULT, CMD_SERVER_NOTIFY_BACK_TRIBUTE, CMD_BACK_TRIBUTE_REQUEST, CMD_BACK_TRIBUTE_RESPONSE, CMD_REQUEST_GAME_INIT_INFO, CMD_PAY_TRIBUTE_NOTIFY_ALL, CMD_BACK_TRIBUTE_NOTIFY_ALL, CMD_NEED_HOSTING_PORKER, CMD_CANCEL_HOSTING_PORKER, CMD_GOLD_SYNC_TO_CLIENT, CMD_SERVER_NOTIFY_GROUND, CMD_SERVER_NOTIFY_MAX_PORKER, CMD_GAME_SEND_CHAT, CMD_GAME_GET_CHAT, 
    };
    
    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.lbwan.game.proto.CmdType)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CmdProtocol.proto\022\024com.lbwan.game.prot" +
      "o*\263\005\n\007CmdType\022\037\n\032CMD_INIT_GAME_DESKTOP_I" +
      "NFO\020\315\010\022\033\n\026CMD_CUT_DOWN_SECS_SYNC\020\316\010\022\033\n\026C" +
      "MD_SUMBIT_SOME_PORKER\020\317\010\022\033\n\026CMD_SUMBIT_N" +
      "ULL_PORKER\020\320\010\022\035\n\030CMD_SUMBIT_PORKER_RESUL" +
      "T\020\321\010\022\033\n\026CMD_GAME_END_OF_RESULT\020\322\010\022\"\n\035CMD" +
      "_SERVER_NOTIFY_PAY_TRIBUTE\020\323\010\022\034\n\027CMD_PAY" +
      "_TRIBUTE_REQUEST\020\324\010\022\033\n\026CMD_PAY_TRIBUTE_R" +
      "ESULT\020\325\010\022#\n\036CMD_SERVER_NOTIFY_BACK_TRIBU" +
      "TE\020\326\010\022\035\n\030CMD_BACK_TRIBUTE_REQUEST\020\327\010\022\036\n\031",
      "CMD_BACK_TRIBUTE_RESPONSE\020\330\010\022\037\n\032CMD_REQU" +
      "EST_GAME_INIT_INFO\020\331\010\022\037\n\032CMD_PAY_TRIBUTE" +
      "_NOTIFY_ALL\020\332\010\022 \n\033CMD_BACK_TRIBUTE_NOTIF" +
      "Y_ALL\020\333\010\022\034\n\027CMD_NEED_HOSTING_PORKER\020\334\010\022\036" +
      "\n\031CMD_CANCEL_HOSTING_PORKER\020\335\010\022\034\n\027CMD_GO" +
      "LD_SYNC_TO_CLIENT\020\336\010\022\035\n\030CMD_SERVER_NOTIF" +
      "Y_GROUND\020\337\010\022!\n\034CMD_SERVER_NOTIFY_MAX_POR" +
      "KER\020\340\010\022\027\n\022CMD_GAME_SEND_CHAT\020\341\010\022\026\n\021CMD_G" +
      "AME_GET_CHAT\020\342\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
