// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResultCodeProtocol.proto

package com.lbwan.game.proto;

public final class ResultCodeProtocol {
  private ResultCodeProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    SUCCESS(0, 0),
    ERR_NORMAL(1, 1),
    ERR_TOKEN(2, 2),
    ERR_PLAYER(3, 3),
    ERR_UNACTION(4, 4),
    ERR_GAME_UNSTART(5, 5),
    ERR_SELECT_RANGE(6, 6),
    ERR_IN_THE_GAME(7, 7),
    RESULT_SELF_GAME_RUNNING(8, 9),
    ;
    
    public static final int SUCCESS_VALUE = 0;
    public static final int ERR_NORMAL_VALUE = 1;
    public static final int ERR_TOKEN_VALUE = 2;
    public static final int ERR_PLAYER_VALUE = 3;
    public static final int ERR_UNACTION_VALUE = 4;
    public static final int ERR_GAME_UNSTART_VALUE = 5;
    public static final int ERR_SELECT_RANGE_VALUE = 6;
    public static final int ERR_IN_THE_GAME_VALUE = 7;
    public static final int RESULT_SELF_GAME_RUNNING_VALUE = 9;
    
    
    public final int getNumber() { return value; }
    
    public static ResultCode valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return ERR_NORMAL;
        case 2: return ERR_TOKEN;
        case 3: return ERR_PLAYER;
        case 4: return ERR_UNACTION;
        case 5: return ERR_GAME_UNSTART;
        case 6: return ERR_SELECT_RANGE;
        case 7: return ERR_IN_THE_GAME;
        case 9: return RESULT_SELF_GAME_RUNNING;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
            public ResultCode findValueByNumber(int number) {
              return ResultCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lbwan.game.proto.ResultCodeProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ResultCode[] VALUES = {
      SUCCESS, ERR_NORMAL, ERR_TOKEN, ERR_PLAYER, ERR_UNACTION, ERR_GAME_UNSTART, ERR_SELECT_RANGE, ERR_IN_THE_GAME, RESULT_SELF_GAME_RUNNING, 
    };
    
    public static ResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ResultCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.lbwan.game.proto.ResultCode)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ResultCodeProtocol.proto\022\024com.lbwan.ga" +
      "me.proto*\271\001\n\nResultCode\022\013\n\007SUCCESS\020\000\022\016\n\n" +
      "ERR_NORMAL\020\001\022\r\n\tERR_TOKEN\020\002\022\016\n\nERR_PLAYE" +
      "R\020\003\022\020\n\014ERR_UNACTION\020\004\022\024\n\020ERR_GAME_UNSTAR" +
      "T\020\005\022\024\n\020ERR_SELECT_RANGE\020\006\022\023\n\017ERR_IN_THE_" +
      "GAME\020\007\022\034\n\030RESULT_SELF_GAME_RUNNING\020\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
